on:
  pull_request:
    types: [auto_merge_enabled]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Check if the PR is approved
        id: approve_check
        run: |
          deno run -A ./approve_check.ts
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_EVENT: ${{ toJson(github.event) }}
    outputs:
      approved: ${{ steps.approve_check.outputs.approved }}

  approve:
    runs-on: ubuntu-latest
    needs: check
    if: ${{ needs.check.outputs.approved == 'true' }}
    steps:
      - run: echo OK
