on:
  pull_request_target:
    types: [auto_merge_enabled]
  merge_group:
    types: [checks_requested]

jobs:
  approve:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - name: Check if the PR is approved
        id: approve_check
        run: |
          deno run -A ./approve_check.ts
        env:
          GH_TOKEN: ${{ secrets.OWNER_TOKEN }}
          GH_EVENT: ${{ toJson(github.event) }}
          GH_REF: ${{ github.ref }}
